# Exercises dataframes

In [166]:
#Import the necessary packages
import pandas as pd

## 1. Soccer

Create a Pandas dataframe containing the `soccer_data`. Every list contains following data: 
- Player name
- Position
- Club
- Goals scored
- Age

Give the columns of the DataFrame appropriate names.

In [167]:
soccer_data = [
    ['Lionel Messi', 'Forward', 'Inter Miami', 30, 12],
    ['Cristiano Ronaldo', 'Forward', 'Al Nassr', 25, 10],
    ['Neymar Jr', 'Forward', 'Al Hilal', 20, 18],
    ['Kylian Mbappe', 'Forward', 'PSG', 35, 15],
    ['Kevin De Bruyne', 'Midfielder', 'Manchester City', 15, 20],
    ['Mohamed Salah', 'Forward', 'Liverpool', 28, 14],
    ['Robert Lewandowski', 'Forward', 'Barcelona', 33, 9],
    ['Karim Benzema', 'Forward', 'Real Madrid', 27, 11],
    ['Luka Modric', 'Midfielder', 'Real Madrid', 10, 22],
    ['Erling Haaland', 'Forward', 'Manchester City', 40, 8]
]

In [168]:
# Create dataframe
cols = ['Player name', 'Position', 'Club', 'Goals scored', 'Age']
df = pd.DataFrame(
    data=soccer_data,
    columns=cols
)
df

          Player name    Position             Club  Goals scored  Age
0        Lionel Messi     Forward      Inter Miami            30   12
1   Cristiano Ronaldo     Forward         Al Nassr            25   10
2           Neymar Jr     Forward         Al Hilal            20   18
3       Kylian Mbappe     Forward              PSG            35   15
4     Kevin De Bruyne  Midfielder  Manchester City            15   20
5       Mohamed Salah     Forward        Liverpool            28   14
6  Robert Lewandowski     Forward        Barcelona            33    9
7       Karim Benzema     Forward      Real Madrid            27   11
8         Luka Modric  Midfielder      Real Madrid            10   22
9      Erling Haaland     Forward  Manchester City            40    8

**Renaming column** \
It seems, we made a mistake. Lionel Messi isn't 12 years old and Kevin De Bruyne isn't 20 either. \
Change the last column's name to "Assists" instead of "Age". Ensure the dataframe itself is affected.

In [169]:
# Renaming column
df.rename(columns={'Age': 'Assists'}, inplace=True)
df

          Player name    Position             Club  Goals scored  Assists
0        Lionel Messi     Forward      Inter Miami            30       12
1   Cristiano Ronaldo     Forward         Al Nassr            25       10
2           Neymar Jr     Forward         Al Hilal            20       18
3       Kylian Mbappe     Forward              PSG            35       15
4     Kevin De Bruyne  Midfielder  Manchester City            15       20
5       Mohamed Salah     Forward        Liverpool            28       14
6  Robert Lewandowski     Forward        Barcelona            33        9
7       Karim Benzema     Forward      Real Madrid            27       11
8         Luka Modric  Midfielder      Real Madrid            10       22
9      Erling Haaland     Forward  Manchester City            40        8

**Change the index labels** to player1, player2 etc.

In [170]:
# Index labels
idx = [f'player{i}' for i in range(1, df.shape[0]+1)]
df.index = idx
df

,Player name,Position,Club,Goals scored,Assists
player1,Lionel Messi,Forward,Inter Miami,30,12
player2,Cristiano Ronaldo,Forward,Al Nassr,25,10
player3,Neymar Jr,Forward,Al Hilal,20,18
player4,Kylian Mbappe,Forward,PSG,35,15
player5,Kevin De Bruyne,Midfielder,Manchester City,15,20
player6,Mohamed Salah,Forward,Liverpool,28,14
player7,Robert Lewandowski,Forward,Barcelona,33,9
player8,Karim Benzema,Forward,Real Madrid,27,11
player9,Luka Modric,Midfielder,Real Madrid,10,22
player10,Erling Haaland,Forward,Manchester City,40,8

## 2. More soccer

This time, the soccer data is stored in a dictionary containing lists. The values of the dictionary, are lists containing the data of a column, the keys are the column names. Create a dataframe using the `soccer_data` below.

In [171]:
soccer_data = {
    'Player Name': [
        'Lionel Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'Kylian Mbappe', 'Kevin De Bruyne', 
        'Mohamed Salah', 'Robert Lewandowski', 'Karim Benzema', 'Luka Modric', 'Erling Haaland'
    ],
    'Player Number': [10, 7, 11, 9, 17, 12, 8, 19, 3, 2],
    'Position': [
        'Forward', 'Forward', 'Forward', 'Forward', 'Midfielder', 
        'Forward', 'Forward', 'Forward', 'Midfielder', 'Forward'
    ],
    'Club': [
        'Inter Miami', 'Al Nassr', 'Al Hilal', 'PSG', 'Manchester City', 
        'Liverpool', 'Barcelona', 'Real Madrid', 'Real Madrid', 'Manchester City'
    ],
    'Goals Scored (Season)': [30, 25, 20, 35, 15, 28, 33, 27, 10, 40],
    'Assists (Season)': [12, 10, 18, 15, 20, 14, 9, 11, 22, 8]
}

In [172]:
# Create DataFrame
df = pd.DataFrame(soccer_data)
df

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
0,Lionel Messi,10,Forward,Inter Miami,30,12
1,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
2,Neymar Jr,11,Forward,Al Hilal,20,18
3,Kylian Mbappe,9,Forward,PSG,35,15
4,Kevin De Bruyne,17,Midfielder,Manchester City,15,20
5,Mohamed Salah,12,Forward,Liverpool,28,14
6,Robert Lewandowski,8,Forward,Barcelona,33,9
7,Karim Benzema,19,Forward,Real Madrid,27,11
8,Luka Modric,3,Midfielder,Real Madrid,10,22
9,Erling Haaland,2,Forward,Manchester City,40,8

You see we have an extra column `Player Number` containing the player's shirt numbers. Use this data to set the index labels. Doing so, you see two dark grey rows on top containing names. Remove the index column name.

❓ Is it a good idea to use the players's numbers as index labels? Why (not)?

In [173]:
# Index labels
df.index = df['Player Number']
# df.reset_index(drop=True, inplace=True)
df

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18
9,Kylian Mbappe,9,Forward,PSG,35,15
17,Kevin De Bruyne,17,Midfielder,Manchester City,15,20
12,Mohamed Salah,12,Forward,Liverpool,28,14
8,Robert Lewandowski,8,Forward,Barcelona,33,9
19,Karim Benzema,19,Forward,Real Madrid,27,11
3,Luka Modric,3,Midfielder,Real Madrid,10,22
2,Erling Haaland,2,Forward,Manchester City,40,8

**Indexing** 
- Display the club of Kevin De Bruyne
- Change the club of Kevin De Bruyne to "Red Devils"
- Display the Player Name column
- Display the data of the player with shirt number 7, using both integer and label position

In [174]:
#Indexing
df[df['Player Name'] == 'Kevin De Bruyne']['Club']
# df.at[4, 'Club']

Player Number
17    Manchester City
Name: Club, dtype: object

In [175]:
df.loc[17, 'Club'] = 'Red Devils'
df

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18
9,Kylian Mbappe,9,Forward,PSG,35,15
17,Kevin De Bruyne,17,Midfielder,Red Devils,15,20
12,Mohamed Salah,12,Forward,Liverpool,28,14
8,Robert Lewandowski,8,Forward,Barcelona,33,9
19,Karim Benzema,19,Forward,Real Madrid,27,11
3,Luka Modric,3,Midfielder,Real Madrid,10,22
2,Erling Haaland,2,Forward,Manchester City,40,8

In [176]:
df['Player Name']

Player Number
10          Lionel Messi
7      Cristiano Ronaldo
11             Neymar Jr
9          Kylian Mbappe
17       Kevin De Bruyne
12         Mohamed Salah
8     Robert Lewandowski
19         Karim Benzema
3            Luka Modric
2         Erling Haaland
Name: Player Name, dtype: object

In [177]:
df.loc[7]

Player Name              Cristiano Ronaldo
Player Number                            7
Position                           Forward
Club                              Al Nassr
Goals Scored (Season)                   25
Assists (Season)                        10
Name: 7, dtype: object

In [178]:
df.iloc[1]

Player Name              Cristiano Ronaldo
Player Number                            7
Position                           Forward
Club                              Al Nassr
Goals Scored (Season)                   25
Assists (Season)                        10
Name: 7, dtype: object

**Slicing** 
- Display the players with shirt number 10, 7 and 11 using both integer and label position
- Display the players with at least 10 assists
- Display all midfield players
- Display the Player Name, Position and Club of Karim, Luka and Erling

In [179]:
#Slicing
df.loc[10:11]

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18

In [180]:
df.iloc[:3]

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18

In [181]:
df[df['Assists (Season)'] >= 10]

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18
9,Kylian Mbappe,9,Forward,PSG,35,15
17,Kevin De Bruyne,17,Midfielder,Red Devils,15,20
12,Mohamed Salah,12,Forward,Liverpool,28,14
19,Karim Benzema,19,Forward,Real Madrid,27,11
3,Luka Modric,3,Midfielder,Real Madrid,10,22

In [182]:
df[df['Position'] == 'Midfielder']

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
Player Number,,,,,,
17,Kevin De Bruyne,17,Midfielder,Red Devils,15,20
3,Luka Modric,3,Midfielder,Real Madrid,10,22

In [183]:
df.loc[19:, ['Player Name', 'Position', 'Club']]

                  Player Name    Position             Club
Player Number
19              Karim Benzema     Forward      Real Madrid
3                 Luka Modric  Midfielder      Real Madrid
2              Erling Haaland     Forward  Manchester City


## 3. Employees
In this lab exercise, you will explore a dataset containing information about employees in a company using Pandas. You will perform various data manipulation and analysis tasks to gain insights into the employee data.

**Dataset:**
You are provided with a dictionary `employee_data` containing employee information:

In [184]:
employee_data = {
    'EmployeeID': [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125, 126, 127, 128, 129, 130
    ],
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack',
        'Katherine', 'Leo', 'Mia', 'Nathan', 'Olivia', 'Paul', 'Quinn', 'Rachel', 'Samuel', 'Tina',
        'Uma', 'Victor', 'Wendy', 'Xander', 'Yasmine', 'Zack', 'Adam', 'Bella', 'Chris', 'Diana'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales'
    ],
    'Salary': [
        60000, 75000, 80000, 70000, 65000, 72000, 68000, 81000, 69000, 66000,
        77000, 64000, 85000, 73000, 67000, 61000, 79000, 82000, 74000, 66000,
        78000, 62000, 83000, 76000, 71000, 63000, 80000, 75000, 87000, 72000
    ]
}

**DataFrame Creation:**
- Create a Pandas DataFrame named 'employees' from the provided dictionary 'employee_data'.
- Use their employee number as row index. Remove the row index column name.

**Data Exploration:**
- Display the first 3 rows of the DataFrame to get an overview of the data. 
- Check the summary statistics for the 'Salary' column. 
- Determine the number of employees in each department.

**Data Analysis:**
- Display the min, max, mean and median of the 'Salary' column.
- Identify the employee(s) with the highest salary and their details.
- Determine the department with the lowest average salary.
- Add a new column 'Salary Increase' to the DataFrame, where each employee's salary is increased by 10%.

In [185]:
# Your code
employees = pd.DataFrame(employee_data,
                         index=employee_data['EmployeeID'])
employees.index.name = None
employees

     EmployeeID       Name Department  Salary
101         101      Alice         HR   60000
102         102        Bob         IT   75000
103         103    Charlie    Finance   80000
104         104      David  Marketing   70000
105         105       Emma      Sales   65000
106         106      Frank         IT   72000
107         107      Grace         HR   68000
108         108     Hannah    Finance   81000
109         109        Ian  Marketing   69000
110         110       Jack      Sales   66000
111         111  Katherine         IT   77000
112         112        Leo         HR   64000
113         113        Mia    Finance   85000
114         114     Nathan  Marketing   73000
115         115     Olivia      Sales   67000
116         116       Paul         HR   61000
117         117      Quinn         IT   79000
118         118     Rachel    Finance   82000
119         119     Samuel  Marketing   74000
120         120       Tina      Sales   66000
121         121        Uma         IT   78000
122         122     Victor         HR   62000
123         123      Wendy    Finance   83000
124         124     Xander  Marketing   76000
125         125    Yasmine      Sales   71000
126         126       Zack         HR   63000
127         127       Adam         IT   80000
128         128      Bella    Finance   75000
129         129      Chris  Marketing   87000
130         130      Diana      Sales   72000

In [186]:
employees.head(3)

     EmployeeID     Name Department  Salary
101         101    Alice         HR   60000
102         102      Bob         IT   75000
103         103  Charlie    Finance   80000

In [187]:
employees["Salary"].describe()

count       30.000000
mean     72700.000000
std       7529.940239
min      60000.000000
25%      66250.000000
50%      72500.000000
75%      78750.000000
max      87000.000000
Name: Salary, dtype: float64

In [188]:
grouped_by_department = employees.groupby('Department')['EmployeeID'].count().reset_index()
grouped_by_department.columns = ['Department', 'Employee Count']
grouped_by_department

  Department  Employee Count
0    Finance               6
1         HR               6
2         IT               6
3  Marketing               6
4      Sales               6

In [189]:
employees['Salary'].agg(['min', 'max', 'mean', 'median'])

min       60000.0
max       87000.0
mean      72700.0
median    72500.0
Name: Salary, dtype: float64

In [190]:
max_salary = employees['Salary'].max()
employees[employees['Salary'] == max_salary]

     EmployeeID   Name Department  Salary
129         129  Chris  Marketing   87000

In [191]:
avg_salary = employees.groupby('Department')['Salary'].mean().reset_index()
avg_salary.rename(columns={'Salary': "Average Salary"}, inplace=True)
avg_salary[avg_salary['Average Salary'] == avg_salary['Average Salary'].min()]

  Department  Average Salary
1         HR         63000.0

In [192]:
employees['Salary Increase'] = employees['Salary'] * 1.1
employees

     EmployeeID       Name Department  Salary  Salary Increase
101         101      Alice         HR   60000          66000.0
102         102        Bob         IT   75000          82500.0
103         103    Charlie    Finance   80000          88000.0
104         104      David  Marketing   70000          77000.0
105         105       Emma      Sales   65000          71500.0
106         106      Frank         IT   72000          79200.0
107         107      Grace         HR   68000          74800.0
108         108     Hannah    Finance   81000          89100.0
109         109        Ian  Marketing   69000          75900.0
110         110       Jack      Sales   66000          72600.0
111         111  Katherine         IT   77000          84700.0
112         112        Leo         HR   64000          70400.0
113         113        Mia    Finance   85000          93500.0
114         114     Nathan  Marketing   73000          80300.0
115         115     Olivia      Sales   67000          73700.0
116         116       Paul         HR   61000          67100.0
117         117      Quinn         IT   79000          86900.0
118         118     Rachel    Finance   82000          90200.0
119         119     Samuel  Marketing   74000          81400.0
120         120       Tina      Sales   66000          72600.0
121         121        Uma         IT   78000          85800.0
122         122     Victor         HR   62000          68200.0
123         123      Wendy    Finance   83000          91300.0
124         124     Xander  Marketing   76000          83600.0
125         125    Yasmine      Sales   71000          78100.0
126         126       Zack         HR   63000          69300.0
127         127       Adam         IT   80000          88000.0
128         128      Bella    Finance   75000          82500.0
129         129      Chris  Marketing   87000          95700.0
130         130      Diana      Sales   72000          79200.0

## 4. Sales data

In [193]:
import numpy as np

sales_data = {
    'Product_ID': list(range(101, 151)),
    'Product_Name': [
        'Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smartwatch', 'Gaming Console', 'Keyboard', 'Mouse', 
        'Monitor', 'Printer', 'Speaker', 'Camera', 'External Hard Drive', 'Router', 'Microphone',
        'Smart TV', 'Projector', 'Power Bank', 'VR Headset', 'Graphics Card', 'Processor', 'RAM', 
        'Motherboard', 'SSD', 'HDD', 'USB Flash Drive', 'Cooling Pad', 'Tripod', 'Streaming Device', 
        'E-Reader', 'Wireless Charger', 'Portable Speaker', 'Game Controller', 'Webcam', 'Smart Light', 
        'Smart Doorbell', 'Fitness Band', 'Drone', 'Bluetooth Adapter', 'Drawing Tablet', 'Coffee Maker', 
        'Air Purifier', 'Robot Vacuum', 'Electric Kettle', 'Blender', 'Toaster', 'Smart Refrigerator', 
        'Washing Machine', 'Oven', 'Microwave'
    ],
    'Category': [
        'Electronics', 'Electronics', 'Electronics', 'Accessories', 'Electronics', 'Gaming', 'Accessories', 
        'Accessories', 'Electronics', 'Office Supplies', 'Audio', 'Photography', 'Storage', 'Networking', 
        'Audio', 'Electronics', 'Office Supplies', 'Accessories', 'Gaming', 'Computer Components', 
        'Computer Components', 'Computer Components', 'Computer Components', 'Storage', 'Storage', 
        'Accessories', 'Accessories', 'Photography', 'Streaming', 'Electronics', 'Accessories', 'Audio', 
        'Gaming', 'Accessories', 'Smart Home', 'Smart Home', 'Wearable', 'Drones', 'Accessories', 
        'Accessories', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 
        'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances',
    ],
    'Price': [
        1200, 800, 400, 100, 300, 500, 50, 40, 250, 150, 200, 700, 120, 90, 60, 1000, 850, 35, 
        600, 400, 300, 150, 200, 180, 130, 20, 45, 100, 120, 250, 75, 220, 55, 90, 200, 180, 
        150, 300, 110, 150, 180, 220, 100, 120, 400, 500, 450, 350, 320
    ],
    'Quantity_Sold': [
        50, 100, 80, 200, 120, 75, 95, np.nan, 60, 110, 130, 40, np.nan, 85, 90, 55, 30, 200, 
        35, np.nan, 65, 45, 100, 70, 85, 150, np.nan, 90, 50, 200, 105, 65, 140, 55, 60, 70, 
        np.nan, 30, 45, 90, 35, 60, 95, np.nan, 110, 75, 55, 80, 100
    ],
    'Brand': [
        'Dell', 'Apple', 'Samsung', 'Sony', 'Fitbit', 'Microsoft', 'Logitech', 'HP', 'LG', 'Canon', 
        'JBL', 'Nikon', 'Seagate', 'TP-Link', 'Blue Yeti', 'Samsung', 'Epson', 'Anker', 'Oculus', 
        'NVIDIA', 'Intel', 'Corsair', 'ASUS', 'Kingston', 'Western Digital', 'SanDisk', 'Cooler Master', 
        'Manfrotto', 'Roku', 'Amazon', 'Belkin', 'Bose', 'Xbox', 'Logitech', 'Philips', 'Ring', 
        'Garmin', 'DJI', 'TP-Link', 'Wacom', 'Keurig', 'Dyson', 'iRobot', 'Breville', 'Ninja', 'Cuisinart', 
        'Samsung', 'LG', 'Bosch', 'Panasonic'
    ],
    'Release_Year': [
        2021, 2020, 2019, 2022, 2021, 2020, 2018, 2017, 2019, 2022, 2021, 2020, 2019, 2021, 2018, 
        2022, 2021, 2020, 2023, 2021, 2019, 2020, 2018, 2022, 2023, 2017, 2018, 2019, 2020, 2021, 
        2018, 2019, 2022, 2020, 2021, 2023, 2022, 2018, 2020, 2019, 2021, 2023, 2020, 2022, 2021, 
        2019, 2018, 2020, 2023
    ],
    'Ratings': [
        4.5, 4.7, 4.3, 4.2, 4.6, 4.8, 4.0, np.nan, 4.1, 4.3, 4.6, 4.7, np.nan, 4.5, 4.0, 
        4.4, 4.1, 3.9, 4.9, np.nan, 4.2, 4.0, 4.3, 4.6, 4.8, 4.1, np.nan, 4.5, 4.2, 4.7, 
        4.0, 4.3, 4.1, 4.6, 4.2, 4.8, 4.9, np.nan, 4.0, 4.1, 4.3, 4.6, 4.2, 4.5, np.nan, 
        4.7, 4.3, 4.2, 4.8
    ]
}

**DataFrame Creation:**
- Create a Pandas DataFrame named 'sales' from the provided dictionary 'sales_data'.
    <details>
    <summary> error? </summary>
    When trying to create a DataFrame, you get an error. The values of the dictionary are not of equal length... Meaning, the last entry/entries is/are incomplete. Omit these entries to create the DataFrame.
    </details>

- Use the Product ID's as index and remove the index heading.
- Set all NaN values in the "Quantity_Sold" column to 0.
- Delete rows containing NaN values except if they only occur in the ratings column. Check the documentation of the known method to delete rows containing NaN's. 
- Show the first 5 rows (without using slicing) and display information about the DataFrame.
- Show the dimensions of the DataFrame

**Indexing and Slicing:**
- Access the last 2 rows and the 'Product_Name' and 'Price' columns using both label-based and positional-based indexing.
- Extract the data for products with product id's 105 to 118 and all columns using integer-based indexing.
    - Don't start counting the rows. It might be useful to reset de indices back to position integers. We still want to keep the Product_ID in our DataFrame, make a new column for this data with an appropriate name.
- **Boolean filtering:** Filter the data to include only products priced below 100.

In [ ]:
# # Your code
# sales = pd.DataFrame(sales_data, index=sales_data['Product_ID'])
# sales.index.name = None
# sales

ValueError: Length of values (49) does not match length of index (50)

In [195]:
for key in sales_data:
    print(f'{key}: {len(sales_data[key])}')

Product_ID: 50
Product_Name: 50
Category: 49
Price: 49
Quantity_Sold: 49
Brand: 50
Release_Year: 49
Ratings: 49

In [196]:
for key in sales_data:
    if len(sales_data[key]) == 50:
        sales_data[key].pop()

In [197]:
for key in sales_data:
    print(f'{key}: {len(sales_data[key])}')

Product_ID: 49
Product_Name: 49
Category: 49
Price: 49
Quantity_Sold: 49
Brand: 49
Release_Year: 49
Ratings: 49

In [198]:
sales = pd.DataFrame(sales_data, index=sales_data['Product_ID'])
sales.index.name = None
sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
101,101,Laptop,Electronics,1200,50.0,Dell,2021,4.5
102,102,Smartphone,Electronics,800,100.0,Apple,2020,4.7
103,103,Tablet,Electronics,400,80.0,Samsung,2019,4.3
104,104,Headphones,Accessories,100,200.0,Sony,2022,4.2
105,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6
106,106,Gaming Console,Gaming,500,75.0,Microsoft,2020,4.8
107,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
108,108,Mouse,Accessories,40,NaN,HP,2017,NaN
109,109,Monitor,Electronics,250,60.0,LG,2019,4.1
110,110,Printer,Office Supplies,150,110.0,Canon,2022,4.3
111,111,Speaker,Audio,200,130.0,JBL,2021,4.6
112,112,Camera,Photography,700,40.0,Nikon,2020,4.7
113,113,External Hard Drive,Storage,120,NaN,Seagate,2019,NaN
114,114,Router,Networking,90,85.0,TP-Link,2021,4.5
115,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
116,116,Smart TV,Electronics,1000,55.0,Samsung,2022,4.4
117,117,Projector,Office Supplies,850,30.0,Epson,2021,4.1
118,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9
119,119,VR Headset,Gaming,600,35.0,Oculus,2023,4.9
120,120,Graphics Card,Computer Components,400,NaN,NVIDIA,2021,NaN
121,121,Processor,Computer Components,300,65.0,Intel,2019,4.2
122,122,RAM,Computer Components,150,45.0,Corsair,2020,4.0
123,123,Motherboard,Computer Components,200,100.0,ASUS,2018,4.3
124,124,SSD,Storage,180,70.0,Kingston,2022,4.6
125,125,HDD,Storage,130,85.0,Western Digital,2023,4.8
126,126,USB Flash Drive,Accessories,20,150.0,SanDisk,2017,4.1
127,127,Cooling Pad,Accessories,45,NaN,Cooler Master,2018,NaN
128,128,Tripod,Photography,100,90.0,Manfrotto,2019,4.5
129,129,Streaming Device,Streaming,120,50.0,Roku,2020,4.2
130,130,E-Reader,Electronics,250,200.0,Amazon,2021,4.7
131,131,Wireless Charger,Accessories,75,105.0,Belkin,2018,4.0
132,132,Portable Speaker,Audio,220,65.0,Bose,2019,4.3
133,133,Game Controller,Gaming,55,140.0,Xbox,2022,4.1
134,134,Webcam,Accessories,90,55.0,Logitech,2020,4.6
135,135,Smart Light,Smart Home,200,60.0,Philips,2021,4.2
136,136,Smart Doorbell,Smart Home,180,70.0,Ring,2023,4.8
137,137,Fitness Band,Wearable,150,NaN,Garmin,2022,4.9
138,138,Drone,Drones,300,30.0,DJI,2018,NaN
139,139,Bluetooth Adapter,Accessories,110,45.0,TP-Link,2020,4.0
140,140,Drawing Tablet,Accessories,150,90.0,Wacom,2019,4.1
141,141,Coffee Maker,Home Appliances,180,35.0,Keurig,2021,4.3
142,142,Air Purifier,Home Appliances,220,60.0,Dyson,2023,4.6
143,143,Robot Vacuum,Home Appliances,100,95.0,iRobot,2020,4.2
144,144,Electric Kettle,Home Appliances,120,NaN,Breville,2022,4.5
145,145,Blender,Home Appliances,400,110.0,Ninja,2021,NaN
146,146,Toaster,Home Appliances,500,75.0,Cuisinart,2019,4.7
147,147,Smart Refrigerator,Home Appliances,450,55.0,Samsung,2018,4.3
148,148,Washing Machine,Home Appliances,350,80.0,LG,2020,4.2
149,149,Oven,Home Appliances,320,100.0,Bosch,2023,4.8

In [199]:
sales['Quantity_Sold'].fillna(0)
sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
101,101,Laptop,Electronics,1200,50.0,Dell,2021,4.5
102,102,Smartphone,Electronics,800,100.0,Apple,2020,4.7
103,103,Tablet,Electronics,400,80.0,Samsung,2019,4.3
104,104,Headphones,Accessories,100,200.0,Sony,2022,4.2
105,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6
106,106,Gaming Console,Gaming,500,75.0,Microsoft,2020,4.8
107,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
108,108,Mouse,Accessories,40,NaN,HP,2017,NaN
109,109,Monitor,Electronics,250,60.0,LG,2019,4.1
110,110,Printer,Office Supplies,150,110.0,Canon,2022,4.3
111,111,Speaker,Audio,200,130.0,JBL,2021,4.6
112,112,Camera,Photography,700,40.0,Nikon,2020,4.7
113,113,External Hard Drive,Storage,120,NaN,Seagate,2019,NaN
114,114,Router,Networking,90,85.0,TP-Link,2021,4.5
115,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
116,116,Smart TV,Electronics,1000,55.0,Samsung,2022,4.4
117,117,Projector,Office Supplies,850,30.0,Epson,2021,4.1
118,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9
119,119,VR Headset,Gaming,600,35.0,Oculus,2023,4.9
120,120,Graphics Card,Computer Components,400,NaN,NVIDIA,2021,NaN
121,121,Processor,Computer Components,300,65.0,Intel,2019,4.2
122,122,RAM,Computer Components,150,45.0,Corsair,2020,4.0
123,123,Motherboard,Computer Components,200,100.0,ASUS,2018,4.3
124,124,SSD,Storage,180,70.0,Kingston,2022,4.6
125,125,HDD,Storage,130,85.0,Western Digital,2023,4.8
126,126,USB Flash Drive,Accessories,20,150.0,SanDisk,2017,4.1
127,127,Cooling Pad,Accessories,45,NaN,Cooler Master,2018,NaN
128,128,Tripod,Photography,100,90.0,Manfrotto,2019,4.5
129,129,Streaming Device,Streaming,120,50.0,Roku,2020,4.2
130,130,E-Reader,Electronics,250,200.0,Amazon,2021,4.7
131,131,Wireless Charger,Accessories,75,105.0,Belkin,2018,4.0
132,132,Portable Speaker,Audio,220,65.0,Bose,2019,4.3
133,133,Game Controller,Gaming,55,140.0,Xbox,2022,4.1
134,134,Webcam,Accessories,90,55.0,Logitech,2020,4.6
135,135,Smart Light,Smart Home,200,60.0,Philips,2021,4.2
136,136,Smart Doorbell,Smart Home,180,70.0,Ring,2023,4.8
137,137,Fitness Band,Wearable,150,NaN,Garmin,2022,4.9
138,138,Drone,Drones,300,30.0,DJI,2018,NaN
139,139,Bluetooth Adapter,Accessories,110,45.0,TP-Link,2020,4.0
140,140,Drawing Tablet,Accessories,150,90.0,Wacom,2019,4.1
141,141,Coffee Maker,Home Appliances,180,35.0,Keurig,2021,4.3
142,142,Air Purifier,Home Appliances,220,60.0,Dyson,2023,4.6
143,143,Robot Vacuum,Home Appliances,100,95.0,iRobot,2020,4.2
144,144,Electric Kettle,Home Appliances,120,NaN,Breville,2022,4.5
145,145,Blender,Home Appliances,400,110.0,Ninja,2021,NaN
146,146,Toaster,Home Appliances,500,75.0,Cuisinart,2019,4.7
147,147,Smart Refrigerator,Home Appliances,450,55.0,Samsung,2018,4.3
148,148,Washing Machine,Home Appliances,350,80.0,LG,2020,4.2
149,149,Oven,Home Appliances,320,100.0,Bosch,2023,4.8

In [201]:
sales.shape

(49, 8)

In [202]:
sales = sales.dropna(subset=['Ratings'])
sales.shape

(43, 8)

In [203]:
sales.head()

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
101,101,Laptop,Electronics,1200,50.0,Dell,2021,4.5
102,102,Smartphone,Electronics,800,100.0,Apple,2020,4.7
103,103,Tablet,Electronics,400,80.0,Samsung,2019,4.3
104,104,Headphones,Accessories,100,200.0,Sony,2022,4.2
105,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6

In [204]:
sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
101,101,Laptop,Electronics,1200,50.0,Dell,2021,4.5
102,102,Smartphone,Electronics,800,100.0,Apple,2020,4.7
103,103,Tablet,Electronics,400,80.0,Samsung,2019,4.3
104,104,Headphones,Accessories,100,200.0,Sony,2022,4.2
105,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6
106,106,Gaming Console,Gaming,500,75.0,Microsoft,2020,4.8
107,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
109,109,Monitor,Electronics,250,60.0,LG,2019,4.1
110,110,Printer,Office Supplies,150,110.0,Canon,2022,4.3
111,111,Speaker,Audio,200,130.0,JBL,2021,4.6
112,112,Camera,Photography,700,40.0,Nikon,2020,4.7
114,114,Router,Networking,90,85.0,TP-Link,2021,4.5
115,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
116,116,Smart TV,Electronics,1000,55.0,Samsung,2022,4.4
117,117,Projector,Office Supplies,850,30.0,Epson,2021,4.1
118,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9
119,119,VR Headset,Gaming,600,35.0,Oculus,2023,4.9
121,121,Processor,Computer Components,300,65.0,Intel,2019,4.2
122,122,RAM,Computer Components,150,45.0,Corsair,2020,4.0
123,123,Motherboard,Computer Components,200,100.0,ASUS,2018,4.3
124,124,SSD,Storage,180,70.0,Kingston,2022,4.6
125,125,HDD,Storage,130,85.0,Western Digital,2023,4.8
126,126,USB Flash Drive,Accessories,20,150.0,SanDisk,2017,4.1
128,128,Tripod,Photography,100,90.0,Manfrotto,2019,4.5
129,129,Streaming Device,Streaming,120,50.0,Roku,2020,4.2
130,130,E-Reader,Electronics,250,200.0,Amazon,2021,4.7
131,131,Wireless Charger,Accessories,75,105.0,Belkin,2018,4.0
132,132,Portable Speaker,Audio,220,65.0,Bose,2019,4.3
133,133,Game Controller,Gaming,55,140.0,Xbox,2022,4.1
134,134,Webcam,Accessories,90,55.0,Logitech,2020,4.6
135,135,Smart Light,Smart Home,200,60.0,Philips,2021,4.2
136,136,Smart Doorbell,Smart Home,180,70.0,Ring,2023,4.8
137,137,Fitness Band,Wearable,150,NaN,Garmin,2022,4.9
139,139,Bluetooth Adapter,Accessories,110,45.0,TP-Link,2020,4.0
140,140,Drawing Tablet,Accessories,150,90.0,Wacom,2019,4.1
141,141,Coffee Maker,Home Appliances,180,35.0,Keurig,2021,4.3
142,142,Air Purifier,Home Appliances,220,60.0,Dyson,2023,4.6
143,143,Robot Vacuum,Home Appliances,100,95.0,iRobot,2020,4.2
144,144,Electric Kettle,Home Appliances,120,NaN,Breville,2022,4.5
146,146,Toaster,Home Appliances,500,75.0,Cuisinart,2019,4.7
147,147,Smart Refrigerator,Home Appliances,450,55.0,Samsung,2018,4.3
148,148,Washing Machine,Home Appliances,350,80.0,LG,2020,4.2
149,149,Oven,Home Appliances,320,100.0,Bosch,2023,4.8

In [205]:
sales.shape

(43, 8)

In [206]:
sales.loc[148:, ['Product_Name', 'Price']]

        Product_Name  Price
148  Washing Machine    350
149             Oven    320

In [207]:
sales.iloc[-2:, [1, 3]]

        Product_Name  Price
148  Washing Machine    350
149             Oven    320

In [210]:
sales = sales.reset_index(drop=True)

In [213]:
sales = sales.drop(columns='index')
sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
0,101,Laptop,Electronics,1200,50.0,Dell,2021,4.5
1,102,Smartphone,Electronics,800,100.0,Apple,2020,4.7
2,103,Tablet,Electronics,400,80.0,Samsung,2019,4.3
3,104,Headphones,Accessories,100,200.0,Sony,2022,4.2
4,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6
5,106,Gaming Console,Gaming,500,75.0,Microsoft,2020,4.8
6,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
7,109,Monitor,Electronics,250,60.0,LG,2019,4.1
8,110,Printer,Office Supplies,150,110.0,Canon,2022,4.3
9,111,Speaker,Audio,200,130.0,JBL,2021,4.6
10,112,Camera,Photography,700,40.0,Nikon,2020,4.7
11,114,Router,Networking,90,85.0,TP-Link,2021,4.5
12,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
13,116,Smart TV,Electronics,1000,55.0,Samsung,2022,4.4
14,117,Projector,Office Supplies,850,30.0,Epson,2021,4.1
15,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9
16,119,VR Headset,Gaming,600,35.0,Oculus,2023,4.9
17,121,Processor,Computer Components,300,65.0,Intel,2019,4.2
18,122,RAM,Computer Components,150,45.0,Corsair,2020,4.0
19,123,Motherboard,Computer Components,200,100.0,ASUS,2018,4.3
20,124,SSD,Storage,180,70.0,Kingston,2022,4.6
21,125,HDD,Storage,130,85.0,Western Digital,2023,4.8
22,126,USB Flash Drive,Accessories,20,150.0,SanDisk,2017,4.1
23,128,Tripod,Photography,100,90.0,Manfrotto,2019,4.5
24,129,Streaming Device,Streaming,120,50.0,Roku,2020,4.2
25,130,E-Reader,Electronics,250,200.0,Amazon,2021,4.7
26,131,Wireless Charger,Accessories,75,105.0,Belkin,2018,4.0
27,132,Portable Speaker,Audio,220,65.0,Bose,2019,4.3
28,133,Game Controller,Gaming,55,140.0,Xbox,2022,4.1
29,134,Webcam,Accessories,90,55.0,Logitech,2020,4.6
30,135,Smart Light,Smart Home,200,60.0,Philips,2021,4.2
31,136,Smart Doorbell,Smart Home,180,70.0,Ring,2023,4.8
32,137,Fitness Band,Wearable,150,NaN,Garmin,2022,4.9
33,139,Bluetooth Adapter,Accessories,110,45.0,TP-Link,2020,4.0
34,140,Drawing Tablet,Accessories,150,90.0,Wacom,2019,4.1
35,141,Coffee Maker,Home Appliances,180,35.0,Keurig,2021,4.3
36,142,Air Purifier,Home Appliances,220,60.0,Dyson,2023,4.6
37,143,Robot Vacuum,Home Appliances,100,95.0,iRobot,2020,4.2
38,144,Electric Kettle,Home Appliances,120,NaN,Breville,2022,4.5
39,146,Toaster,Home Appliances,500,75.0,Cuisinart,2019,4.7
40,147,Smart Refrigerator,Home Appliances,450,55.0,Samsung,2018,4.3
41,148,Washing Machine,Home Appliances,350,80.0,LG,2020,4.2
42,149,Oven,Home Appliances,320,100.0,Bosch,2023,4.8

In [214]:
sales.iloc[4:16]

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
4,105,Smartwatch,Electronics,300,120.0,Fitbit,2021,4.6
5,106,Gaming Console,Gaming,500,75.0,Microsoft,2020,4.8
6,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
7,109,Monitor,Electronics,250,60.0,LG,2019,4.1
8,110,Printer,Office Supplies,150,110.0,Canon,2022,4.3
9,111,Speaker,Audio,200,130.0,JBL,2021,4.6
10,112,Camera,Photography,700,40.0,Nikon,2020,4.7
11,114,Router,Networking,90,85.0,TP-Link,2021,4.5
12,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
13,116,Smart TV,Electronics,1000,55.0,Samsung,2022,4.4
14,117,Projector,Office Supplies,850,30.0,Epson,2021,4.1
15,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9

In [215]:
sales[sales['Price'] < 100]

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
6,107,Keyboard,Accessories,50,95.0,Logitech,2018,4.0
11,114,Router,Networking,90,85.0,TP-Link,2021,4.5
12,115,Microphone,Audio,60,90.0,Blue Yeti,2018,4.0
15,118,Power Bank,Accessories,35,200.0,Anker,2020,3.9
22,126,USB Flash Drive,Accessories,20,150.0,SanDisk,2017,4.1
26,131,Wireless Charger,Accessories,75,105.0,Belkin,2018,4.0
28,133,Game Controller,Gaming,55,140.0,Xbox,2022,4.1
29,134,Webcam,Accessories,90,55.0,Logitech,2020,4.6

### 4. Sales data part 2

* Read in the additional sales data, stored in the csv file "sales_data.csv" and create a new DataFrame.
* Inspect the file before reading in the data!
* Combine the first sales DataFrame with this new DataFrame in a DataFrame `all_sales`. Ensure both DataFrames are combined correctly. The resulting DataFrame should be of shape 149x8.
* Sort the data from eldest to newest
* Reset the indices to their integer positions, without adding an extra column with the current index label
* Write the resulting DataFrame to a new csv file "all_sales.csv".

In [220]:
# Sales data part 2
sales = pd.read_csv("sales_data.csv",
                    sep=',',
                    index_col=0)
sales.index.name = None
sales
# Your code

,Product ID,Product Name,Category,Price,Quantity Sold,Brand,Release Year,Ratings
1,153,Microwave,Office Supplies,286.26,12,Philips,2015,3.5
2,114,Smart Light,Wearable,248.16,177,Samsung,2016,3.7
3,286,USB Flash Drive,Audio,1012.20,117,HP,2020,3.9
4,128,External Hard Drive,Wearable,839.11,40,JBL,2017,3.5
5,126,Monitor,Electronics,737.47,372,Apple,2023,4.8
...,...,...,...,...,...,...,...,...
96,138,Monitor,Accessories,1439.31,386,Apple,2022,3.9
97,299,Game Controller,Electronics,737.15,289,Dyson,2016,5.0
98,252,Smart Refrigerator,Electronics,1369.96,360,iRobot,2017,4.9
99,104,Blender,Audio,1423.44,51,Apple,2022,4.0
100,181,Electric Kettle,Photography,517.22,148,Sony,2015,NaN

In [219]:
all_sales = pd.read_csv("all_sales.csv",
                    sep=',',
                    index_col=0)
all_sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
0,181,Electric Kettle,Photography,517.22,148.0,Sony,2015,NaN
1,204,VR Headset,Home Appliances,1346.66,448.0,Logitech,2015,4.9
2,275,Toaster,Photography,828.41,414.0,Seagate,2015,4.1
3,152,RAM,Smart Home,454.51,162.0,TP-Link,2015,4.0
4,153,Microwave,Office Supplies,286.26,12.0,Philips,2015,3.5
...,...,...,...,...,...,...,...,...
144,299,Smart Doorbell,Smart Home,976.03,169.0,Dell,2023,4.5
145,154,Smartphone,Wearable,1383.74,302.0,Canon,2023,4.6
146,136,Smart Doorbell,Smart Home,180.00,70.0,Ring,2023,4.8
147,119,VR Headset,Gaming,600.00,35.0,Oculus,2023,4.9
148,168,Smartwatch,Audio,756.07,426.0,Bose,2023,NaN

In [221]:
all_sales = all_sales.sort_values(by='Release_Year', ascending=True)
all_sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
0,181,Electric Kettle,Photography,517.22,148.0,Sony,2015,NaN
1,204,VR Headset,Home Appliances,1346.66,448.0,Logitech,2015,4.9
2,275,Toaster,Photography,828.41,414.0,Seagate,2015,4.1
3,152,RAM,Smart Home,454.51,162.0,TP-Link,2015,4.0
4,153,Microwave,Office Supplies,286.26,12.0,Philips,2015,3.5
...,...,...,...,...,...,...,...,...
134,296,Fitness Band,Smart Home,952.35,287.0,Dyson,2023,4.0
133,252,Smart TV,Home Appliances,1295.23,16.0,Blue Yeti,2023,4.1
147,119,VR Headset,Gaming,600.00,35.0,Oculus,2023,4.9
139,119,Smart Doorbell,Networking,1217.54,372.0,Breville,2023,4.5
148,168,Smartwatch,Audio,756.07,426.0,Bose,2023,NaN

In [224]:
all_sales.reset_index(drop=True, inplace=True)

In [225]:
all_sales.to_csv("all_sales.csv", index=False)
new_all_sales = pd.read_csv("all_sales.csv")
new_all_sales

,Product_ID,Product_Name,Category,Price,Quantity_Sold,Brand,Release_Year,Ratings
0,181,Electric Kettle,Photography,517.22,148.0,Sony,2015,NaN
1,204,VR Headset,Home Appliances,1346.66,448.0,Logitech,2015,4.9
2,275,Toaster,Photography,828.41,414.0,Seagate,2015,4.1
3,152,RAM,Smart Home,454.51,162.0,TP-Link,2015,4.0
4,153,Microwave,Office Supplies,286.26,12.0,Philips,2015,3.5
...,...,...,...,...,...,...,...,...
144,296,Fitness Band,Smart Home,952.35,287.0,Dyson,2023,4.0
145,252,Smart TV,Home Appliances,1295.23,16.0,Blue Yeti,2023,4.1
146,119,VR Headset,Gaming,600.00,35.0,Oculus,2023,4.9
147,119,Smart Doorbell,Networking,1217.54,372.0,Breville,2023,4.5
148,168,Smartwatch,Audio,756.07,426.0,Bose,2023,NaN

#### About the dataset

Did you notice something odd?
<details>
  <summary>No</summary>
  Take a closer look!
</details>

<details>
  <summary>Yes</summary>
  An Electric Kettle in the category Photography? An Apple Blender in the category Audio? This seems rather odd. We have to admit, we asked ChatGPT to generate 100 additional entries of sample data in 'csv' format. Surprisingly we got a generated csv as response, easy peasy right? Yes but no...

  ChatGPT knew some context (programming in Python) when generating the csv. Let's take a look at the analysis of the reasoning of ChatGPT. What do you see?

  ![GenAI analysis reasoning](analysis.png)

  The dataset is generated using Python code and relies on numpy random. Therefore, there is no correlation between the Product, Product ID, Category, Brand etc. 

  The moral of the story: GenAI results might seem good or qualitative, but take a closer look, be sceptic and check out the reasoning to confirm the quality.


</details>